# Generated by Django 4.0.4 on 2022-06-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('Stream_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Stream_name', models.CharField(max_length=20)),
                ('Total_Sem', models.CharField(max_length=2)),
                ('Total_year', models.CharField(max_length=2)),
            ],
        ),
    ]
