# Generated by Django 4.0.4 on 2022-06-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='Stream_name',
            field=models.CharField(max_length=50),
        ),
    ]
