# Generated by Django 4.0.4 on 2022-06-15 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_alter_stream_stream_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='Total_Sem',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stream',
            name='Total_year',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('Sub_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Sub_name', models.CharField(max_length=100)),
                ('Stream_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.stream')),
            ],
        ),
    ]
