# Generated by Django 4.0.4 on 2022-06-16 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_alter_stream_total_sem_alter_stream_total_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('Topic_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Topic_name', models.CharField(max_length=100)),
                ('Sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.subject')),
            ],
        ),
    ]
