# Generated by Django 4.0.4 on 2022-06-16 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Roll', models.IntegerField(max_length=30, primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.IntegerField(max_length=12)),
                ('Name', models.CharField(max_length=100)),
                ('Year', models.IntegerField(max_length=2)),
                ('Password', models.CharField(max_length=100)),
                ('Stream_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.stream')),
            ],
        ),
    ]
