# Generated by Django 4.0.4 on 2022-06-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0006_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='Roll',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='Year',
            field=models.IntegerField(),
        ),
    ]
