# Generated by Django 4.0.4 on 2022-06-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0007_alter_student_phone_alter_student_roll_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Year',
            new_name='Year_OF_PAASING',
        ),
        migrations.AddField(
            model_name='student',
            name='College',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
