# Generated by Django 4.0.4 on 2022-06-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0009_college_remove_student_college_remove_student_roll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='College_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
