# Generated by Django 4.0.4 on 2022-06-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0010_alter_college_college_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='College_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
