# Generated by Django 4.0.4 on 2022-06-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0011_alter_college_college_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='College_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
