# Generated by Django 4.0.4 on 2022-06-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0012_alter_college_college_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Email',
            field=models.CharField(max_length=40),
        ),
    ]
