# Generated by Django 4.0.4 on 2022-06-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0013_alter_teacher_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Email',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
