# Generated by Django 4.0.4 on 2022-06-20 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0014_remove_teacher_id_alter_teacher_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='College_id',
            new_name='Student_College_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Email',
            new_name='Student_Email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Name',
            new_name='Student_Name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Password',
            new_name='Student_Password',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Phone',
            new_name='Student_Phone',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Stream_id',
            new_name='Student_Stream_id',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Year_OF_PAASING',
            new_name='Student_Year_OF_PAASING',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Email',
            new_name='Teacher_Email',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Name',
            new_name='Teacher_Name',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Password',
            new_name='Teacher_Password',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='Phone',
            new_name='Teacher_Phone',
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Notes_id', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('Approved', models.BooleanField()),
                ('Stream_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.stream')),
                ('Sub_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.subject')),
                ('Teacher_Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Notes.teacher')),
            ],
        ),
    ]
